[package]
name = "text-generation-router"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "text-generation-router"
path = "src/main.rs"

[dependencies]
axum = { version = "0.5.16", features = ["json", "serde_json"] }
bloom-inference-client = { path = "client" }
futures = "0.3.24"
parking_lot = "0.12.1"
serde = "1.0.145"
serde_json = "1.0.85"
thiserror = "1.0.37"
tokenizers = "0.13.0"
tokio = { version = "1.21.1", features = ["rt-multi-thread", "parking_lot", "sync"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"

[workspace]
members = [
    "client",
]

[profile.release]
debug = 1
incremental = true
lto = "off"
