[package]
name = "text-generation-launcher"
version = "0.2.0"
edition = "2021"
authors = ["Olivier Dehaene"]
description = "Text Generation Launcher"

[dependencies]
clap = { version = "4.0.15", features = ["derive", "env"] }
ctrlc = { version = "3.2.3", features = ["termination"] }
serde_json = "1.0.89"
subprocess = "0.2.9"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["json"] }

[dev-dependencies]
float_eq = "1.0.1"
reqwest = { version = "0.11.13", features = ["blocking", "json"] }
serde = { version = "1.0.150", features = ["derive"]  }
