[package]
name = "bloom-inference-client"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.24"
#grpc-error-details = { path = "../../grpc-error-details" }
#grpc-metadata = { path = "../../grpc-metadata" }
prost = "^0.9"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["sync"] }
tonic = "^0.6"
tower = "^0.4"
tracing = "^0.1"
tracing-error = "^0.2"

[build-dependencies]
tonic-build = "0.6.2"
